apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-capston-ui-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-capston-ui
  ports:
    - port: {{ .Values.ui.ServicePort }}
      targetPort: {{ .Values.ui.port }} 