apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-capston-todo-get-task-api
spec:
  replicas: {{ .Values.backend_Task.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-capston-todo-get-task-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-capston-todo-get-task-api
    spec:
      containers:
      - name: {{ .Release.Name }}-capston-todo-get-task-api
        image: "{{ .Values.common.containerRegistryURL }}/{{ .Values.getTask.image.name }}:{{ .Values.getTask.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend_Task.port }}
        env: 
        - name: CONNECTION_STRING
          value: "{{ .Values.getTask.connectionString }}"
          