apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-capston-todo-get-task-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-capston-todo-get-task-api
  ports:
    - port: {{ .Values.getTask.ServicePort }}
      targetPort: {{ .Values.getTask.port }}